// Code generated by go-swagger; DO NOT EDIT.

package graphql

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new graphql API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for graphql API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
WeaviateGraphqlBatchPost gets a response based on a batch array of graph q l objects

Get a response based on a batch array of GraphQL objects
*/
func (a *Client) WeaviateGraphqlBatchPost(params *WeaviateGraphqlBatchPostParams, authInfo runtime.ClientAuthInfoWriter) (*WeaviateGraphqlBatchPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewWeaviateGraphqlBatchPostParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "weaviate.graphql.batch.post",
		Method:             "POST",
		PathPattern:        "/graphql/batch",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WeaviateGraphqlBatchPostReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*WeaviateGraphqlBatchPostOK), nil

}

/*
WeaviateGraphqlPost gets a response based on graph q l

Get an object based on GraphQL
*/
func (a *Client) WeaviateGraphqlPost(params *WeaviateGraphqlPostParams, authInfo runtime.ClientAuthInfoWriter) (*WeaviateGraphqlPostOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewWeaviateGraphqlPostParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "weaviate.graphql.post",
		Method:             "POST",
		PathPattern:        "/graphql",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &WeaviateGraphqlPostReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*WeaviateGraphqlPostOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
