/*                          _       _
 *__      _____  __ ___   ___  __ _| |_ ___
 *\ \ /\ / / _ \/ _` \ \ / / |/ _` | __/ _ \
 * \ V  V /  __/ (_| |\ V /| | (_| | ||  __/
 *  \_/\_/ \___|\__,_| \_/ |_|\__,_|\__\___|
 *
 * Copyright © 2016 - 2018 Weaviate. All rights reserved.
 * LICENSE: https://github.com/creativesoftwarefdn/weaviate/blob/develop/LICENSE.md
 * AUTHOR: Bob van Luijt (bob@kub.design)
 * See www.creativesoftwarefdn.org for details
 * Contact: @CreativeSofwFdn / bob@kub.design
 */
// Code generated by go-swagger; DO NOT EDIT.

package graphql

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/creativesoftwarefdn/weaviate/models"
)

// WeaviateGraphqlBatchPostOKCode is the HTTP code returned for type WeaviateGraphqlBatchPostOK
const WeaviateGraphqlBatchPostOKCode int = 200

/*WeaviateGraphqlBatchPostOK Succesful query (with select).

swagger:response weaviateGraphqlBatchPostOK
*/
type WeaviateGraphqlBatchPostOK struct {

	/*
	  In: Body
	*/
	Payload *models.GraphQLResponse `json:"body,omitempty"`
}

// NewWeaviateGraphqlBatchPostOK creates WeaviateGraphqlBatchPostOK with default headers values
func NewWeaviateGraphqlBatchPostOK() *WeaviateGraphqlBatchPostOK {

	return &WeaviateGraphqlBatchPostOK{}
}

// WithPayload adds the payload to the weaviate graphql batch post o k response
func (o *WeaviateGraphqlBatchPostOK) WithPayload(payload *models.GraphQLResponse) *WeaviateGraphqlBatchPostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the weaviate graphql batch post o k response
func (o *WeaviateGraphqlBatchPostOK) SetPayload(payload *models.GraphQLResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WeaviateGraphqlBatchPostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// WeaviateGraphqlBatchPostUnauthorizedCode is the HTTP code returned for type WeaviateGraphqlBatchPostUnauthorized
const WeaviateGraphqlBatchPostUnauthorizedCode int = 401

/*WeaviateGraphqlBatchPostUnauthorized Unauthorized or invalid credentials.

swagger:response weaviateGraphqlBatchPostUnauthorized
*/
type WeaviateGraphqlBatchPostUnauthorized struct {
}

// NewWeaviateGraphqlBatchPostUnauthorized creates WeaviateGraphqlBatchPostUnauthorized with default headers values
func NewWeaviateGraphqlBatchPostUnauthorized() *WeaviateGraphqlBatchPostUnauthorized {

	return &WeaviateGraphqlBatchPostUnauthorized{}
}

// WriteResponse to the client
func (o *WeaviateGraphqlBatchPostUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// WeaviateGraphqlBatchPostForbiddenCode is the HTTP code returned for type WeaviateGraphqlBatchPostForbidden
const WeaviateGraphqlBatchPostForbiddenCode int = 403

/*WeaviateGraphqlBatchPostForbidden The used API-key has insufficient permissions.

swagger:response weaviateGraphqlBatchPostForbidden
*/
type WeaviateGraphqlBatchPostForbidden struct {
}

// NewWeaviateGraphqlBatchPostForbidden creates WeaviateGraphqlBatchPostForbidden with default headers values
func NewWeaviateGraphqlBatchPostForbidden() *WeaviateGraphqlBatchPostForbidden {

	return &WeaviateGraphqlBatchPostForbidden{}
}

// WriteResponse to the client
func (o *WeaviateGraphqlBatchPostForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// WeaviateGraphqlBatchPostUnprocessableEntityCode is the HTTP code returned for type WeaviateGraphqlBatchPostUnprocessableEntity
const WeaviateGraphqlBatchPostUnprocessableEntityCode int = 422

/*WeaviateGraphqlBatchPostUnprocessableEntity Request body contains well-formed (i.e., syntactically correct), but semantically erroneous. Are you sure the class is defined in the configuration file?

swagger:response weaviateGraphqlBatchPostUnprocessableEntity
*/
type WeaviateGraphqlBatchPostUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewWeaviateGraphqlBatchPostUnprocessableEntity creates WeaviateGraphqlBatchPostUnprocessableEntity with default headers values
func NewWeaviateGraphqlBatchPostUnprocessableEntity() *WeaviateGraphqlBatchPostUnprocessableEntity {

	return &WeaviateGraphqlBatchPostUnprocessableEntity{}
}

// WithPayload adds the payload to the weaviate graphql batch post unprocessable entity response
func (o *WeaviateGraphqlBatchPostUnprocessableEntity) WithPayload(payload *models.ErrorResponse) *WeaviateGraphqlBatchPostUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the weaviate graphql batch post unprocessable entity response
func (o *WeaviateGraphqlBatchPostUnprocessableEntity) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WeaviateGraphqlBatchPostUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
